### ISSUE TITLE
vote totals for candidate spread across multiple lines (election day, early voting, etc)

### ISSUE THREAD

**Issue by tamilyn** [openelections/openelections-data-ar#2]
the vote totals for the county are correct when all counties are summed up by candidate.  however that total for each candidate may be broken down into multiple lines - for instance it appears that the votes totals are broken down by election day, absentee voting, early voting etc.   there is nothing in the file to show the differences.  for instance, in AR, Arkansas county, BAYOU METO, there are 3 lines for Hillary.    Those lines are sum up to the correct value but it's probably not what people would expect

**Comment by dwillis** [comment]
In those cases ideally we'd still have a single line per candidate per precinct, but with a `votes` column representing the total number of votes and additional columns representing the types of votes (election day, absentee, early, etc). That doable?

**Comment by tamilyn** [comment]
Yes, that shouldn't be too hard, and would be good to capture the additional info in the data file.
